import Head from 'next/head'
import Image from 'next/image'
import { Inter, Roboto_Mono } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {Row, Col, Container} from 'react-bootstrap';

const inter = Roboto_Mono({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.Inicio}>
          <div className={styles.Texto}>
            <p>Somos uma ONG que quer</p>
            <h1>SALVAR <a href="#vidas">AS VIDAS</a>, DOS MAIS <a href='#vulnerabilidade'>VULNERÁVEIS</a> DA MANEIRA MAIS <a href="#efetividade">EFETIVA</a></h1>
            <p>Todo dia mais de 3 mil pessoas morrem desnecessariamente, de causas evitáveis no Brasil. Quer nos ajudar a mudar essa realidade?</p>
          </div>
        </div>
        <div className={styles.Descricao}>
          <div>
            <div id="vidas" style={{paddingTop: '20px', paddingBottom: '20px'}}>
              <h2>Most popular car rental deals</h2>
              <p>A high-performing web-based car rental system for any rent-a-car company and website. A high-performing web-based car rental system for any rent-a-car company and website. A high-performing web-based car rental system for any rent-a-car company and website</p>
            </div>
            <div id="vulnerabilidade" style={{paddingTop: '20px', paddingBottom: '20px'}}>
              <h2>Most popular car rental deals</h2>
              <p>A high-performing web-based car rental system for any rent-a-car company and website. A high-performing web-based car rental system for any rent-a-car company and website. A high-performing web-based car rental system for any rent-a-car company and website</p>
            </div>
            <div id="efetividade" style={{paddingTop: '20px', paddingBottom: '20px'}}>
              <h2>Most popular car rental deals</h2>
              <p>A high-performing web-based car rental system for any rent-a-car company and website. A high-performing web-based car rental system for any rent-a-car company and website. A high-performing web-based car rental system for any rent-a-car company and website</p>
            </div>
          </div>
          
            <h2>Como funciona</h2>
            <p>Conheça algumas histórias do que já fizemos com mensageria em saúde.</p>
            <h2>Histórias</h2>
            <p>Conheça algumas histórias do que já fizemos com mensageria em saúde.</p>
            <h2>Apoiadores</h2>
        </div>
        
      </main>
    </>
  )
}
